### ISSUE TITLE
Identify cadence for DPG Standard updates

### ISSUE THREAD

**Issue by jwflory** [DPGAlliance/DPG-Standard#125]
# Summary

Identify a cadence or release schedule for new updates and changes made to the DPG Standard.

# Background

In the April Standard Council meeting, @prajectory mentioned the ongoing work to codify the governance around the Standard and the process used to make changes and revisions. One possible way to streamline this is by identifying a cadence in which we periodically review feedback and proposals made to the DPG Standard, and if needed, release a new update. Ideally, as a Standard, formal updates are few and infrequent, but a regular cadence allows us to work through a backlog of feedback.

For context, there are many other FOSS projects where this might be modeled. The [CHAOSS Project](https://chaoss.community/about/), which produces [metrics](https://chaoss.community/metrics/) about open source community health, [releases twice a year](https://chaoss.community/release-history/) through a formal review process. [Fedora Linux](https://docs.fedoraproject.org/en-US/project/), a DPG, makes [two major releases](https://docs.fedoraproject.org/en-US/releases/) of their operating system appx. every six months. Perhaps twice yearly or quarterly could be a good cadence depending on the backlog and capacity of the team.

# Details

A few thoughts on how this work might be completed:

1. Conduct desk review of all pending feedback, proposals, and amendments to the DPG Standard.
2. Reach quorum on a release cadence for the Standard.
3. Consider scoping out dedicated time for part of the release process, e.g. proposal phase, review phase, final vote phase, etc.
4. Begin review of proposals for the next targeted release.

# Outcome

- Improved program management around the DPG Standard.
- Suggestions and feedback on the DPG Standard are regularly reviewed and incorporated when necessary.

**Comment by prajectory** [comment]
Linking some files here that need to be updated to this end: 

https://github.com/DPGAlliance/DPG-Standard/blob/main/CHANGELOG.md 
https://github.com/DPGAlliance/DPG-Standard/blob/main/governance.md

Let's discuss in the DPG reviewer check-in and scope this out > update this thread? Adding to the agenda.

**Comment by prajectory** [comment]
Linking this for discussion https://github.com/DPGAlliance/DPG-Standard/issues/124

**Comment by prajectory** [comment]
Program management on the standard, https://github.com/orgs/DPGAlliance/projects/3/views/2

**Comment by prajectory** [comment]
Hi, closing this issue since we have deployed the Projects board and labels for the Standard updates.
