### ISSUE TITLE
Clarify the term "mandatory dependencies" 

### ISSUE THREAD

**Issue by Lucyeoh** [DPGAlliance/DPG-Standard#129]
Clarify in indicator 4 what we mean by "mandatory dependencies" in plain-language i.e. the solution can't perform it's core function without this component or "the solution doesn't work without this component". 

The solution can't run & function without this. 

Define mandatory dependency (hard dependency Vs.  soft dependency > once we care hard dependency? Is there open alternative? How do we fix this hard dependency) in submission form and significant change the core product

How hard is it for it to be prohibitive for someone else to pick up?

**Comment by prajectory** [comment]
Should we add questions for self assessment of "soft" Vs. "hard" dependancy?

**Comment by prajectory** [comment]
We have created a [checklist](https://docs.google.com/document/d/1tECKjQA0WtD8X2RqteZsBEoH5n6WsZzG4BsdIaIsytQ/edit#heading=h.bromza32mbnz) under indicator 4 and clarified the "primary Vs. secondary"/ "hard Vs. soft" dependency. 

We have also given a clear a hint in the application form:
Please provide a list the active open alternatives for the closed component(s) and demonstrate that these close component(s) can be replaced with those open alternatives with minimal configuration changes, without requiring a major overhaul of the entire system. This requirement can be best answered by a technical member of your team.

Closing this issue.
