### ISSUE TITLE
Role of Sustainability of a DPG

### ISSUE THREAD

**Issue by pamodm** [DPGAlliance/DPG-Standard#131]
The list of indicators suggest a set of criteria against which a solution can be assessed before someone or organization decides to adopt that solution.

I feel in order to achieve SDGs, the role of ministries adopting DPGs is crucial compared to the adoption of individuals or small organizations. With my experience engaging with ministries, I believe in addition to the current list of indicators, 'Sustainability of a DPG' is a major factor factor which determines adoption of a solution. This was also the belief of the HISP network.

Therefore one or more indicators related to sustainability (eg: community, capacity-building, support, funding, adoption) should be included in the core indicators list. This will even facilitate countries who plan to include this list of indicators in the process of procurement of information systems.

**Comment by jstclair2019** [comment]
I think Pamod makes an excellent observation. The Linux Foundation has seen various factors that contribute to sustainability to consider, and we typically have an associated Technical Steering Committee for each project to assess its development and sustainability "stage" to identify early if a DPG's sustainability is in question, especially depending on the level of participation and code commits. 
I'm happy to offer examples of the metrics we collect to assist with this indicator, if desired.

**Comment by prajectory** [comment]
Thanks Pamod and Jim for your inputs on this. We are looking into governance, community and other aspects for why a DPG becomes viably sustainable. Given that DPGs also have an implementation side and various maturity models are used to assess "sustainability" on that front as well, this is a slightly more complicated. 

It is going to be important to define what sustainability means for DPGs. Think through whether the common principles, metrics of sustainability for other open source project apply to DPGs universally or DPGs need to be treated differently - have additional criteria. 

Anyway, I am going to soon slot this for our standard council to mull over and add more comments here. 

Would @jstclair2019 and @pamodm be able to attend the council meeting and give their expertise on the matter? It will not be before end of July.

**Comment by jstclair2019** [comment]
I would be very happy to participate, end of July is still open for planning.

**Comment by pamodm** [comment]
@prajectory thanx 👍 sure, happy to attend and share my ideas.

**Comment by ricardomiron** [comment]
Closing this as we have moved to an ongoing discussion on maturity assessment and integration into the DPG registry but not directly to the DPG Standard
