### ISSUE TITLE
Typos in standard.md

### ISSUE THREAD

**Issue by cjbackman** [DPGAlliance/DPG-Standard#134]
Hi,

I found two potential typos in the file `standard.md`, under item 6 and 9a respectively.

## Item 6

Current:
> [...] Digital public goods with **non personally** identifiable information (PII) [...]

Suggested change:
> [...] Digital public goods with **non-personally** identifiable information (PII) [...]

## Item 9a

Current:
> [...] adverse impacts resulting from **it’s** collection [...]

Suggested change:
> [...] adverse impacts resulting from **its** collection [...]

Cheers,
CJ

**Comment by nathanbaleeta** [comment]
Thanks @cjbackman, nice catch!

**Comment by prajectory** [comment]
Changes executed via https://github.com/DPGAlliance/DPG-Standard/pull/160
