### ISSUE TITLE
Query: End (Digital) Slavery??

### ISSUE THREAD

**Issue by mediaprophet** [DPGAlliance/DPG-Standard#167]
Whilst the broad concept of 'digital slavery' has many different aspects relating to it; one of the more important facets, is to address the need to ensure that people are provided support to be entitled the right to be paid fairly for useful works that they produce.

I wondered how your works ensured that people were supported in retaining the right to be paid fairly for useful works? 

The considerations, whilst complex and part of the foundational considerations related to the body of work that i've been progressing slowely (lack of resources, etc); is that, if people do useful work for the public good - that shouldn't require them to both be unpaid and without acknowledgement for their works; and in-turn also fund the costs related to the production of producing those works; as a form of polarised alternative to proprietary works, that may seek to gain rents / incomes in perpetuity. 

Whilst there are various in-depth and complex related works that i've been involved in developing over many years to address this and other problems relating to ensuring support for rule of law, access / accessibility to lawful remedy, and more broadly support for https://github.com/unicode-org/udhr/ and other related values credentials / instruments; i wondered if your group was actively investigating potential means to address these sorts of considerations.  Noting also, the advent of the industrial era brought about a change in taxation systems; which led to income tax, the 8 hour movement and various other advancements; however the needs for knowledge workers, on international platforms, interactively with various kinds of AI agents, is different; but nonetheless, relates both to socio-economics for persons, as well as states (no income = costs, rather than tax income.  something that UBI like approaches does not address). 

this in-turn, also gives rise to various temporal considerations; both, provonance, and in-turn also, people may not understand the value of a body of work when it is first created; yet, if that work is later found to be invaluable, that should not necessarily means, the creator of the body of work, should not be attributed with socio-economic considerations - as is otherwise demonstrated, in various other fields of human endevour (ie: discoveries, that are written about in books, but only better understood much later on).  

The primary contention is, that persons should be paid fairly for works relating to 'technology for public good' and otherwise; and that whilst fees should not be necessarily made attributable to all types of agents universally (ie: license may stipulate, that fees are applicable to particular types of entities, and not others); that the consequence of the intended consideration be, that, for instance, stone-masons might be paid to build a university, but they don't own it.  

Therein, people might contribute towards the development of advanced cyber-related tooling for the public good, but once they've been paid whatever is defined as 'fair terms', then the license for those works might change to something where there is no-longer any fees associated with its use by any agent, etc.  

in anycase; there are complex considerations related to this field of endevour; and, i would welcome an opportunity to collaborate, cooperatively, towards forming some sort of broad ranging method to address it, and thereby also, support ESG / SDG related 'Verifiable Credentials' that are able to be associated with supply-chain ideologies, business systems, etc.

**Comment by ricardomiron** [comment]
There's not direct relationship to the DPG Standard, so I'm closing this issue
