### ISSUE TITLE
Remove the word "Support" standards to "adhere" or "align with"

### ISSUE THREAD

**Issue by JaniceDean** [DPGAlliance/DPG-Standard#32]
For the question, does the projects support standards, could we replace "support" to "align with" or "adhere to"? One of the nominees was confused by this wording.

**Comment by lacabra** [comment]
Thanks @JaniceDean for the suggestion. Please go ahead and edit the [relevant file](https://github.com/DPGAlliance/DPG-Standard/blob/master/standard-questions.md) and make the suggested edit. When you try to save the changes, it will direct you to open a Pull Request, and that is our call to action to review the proposed changes, discuss them and accept them where appropriate.

**Comment by nathanbaleeta** [comment]
@lacabra a discussion on this topic resolved to leaving it as it is. Kindly refer [here](https://github.com/DPGAlliance/DPG-Standard/pull/34#issuecomment-747494134).
