### ISSUE TITLE
Proposed change to wording for questions for indicator 7

### ISSUE THREAD

**Issue by Lucyeoh** [DPGAlliance/DPG-Standard#35]
Change the question for 7 to: 

* Has this project taken steps to ensure adherence with relevant privacy, domestic, and international laws? (yes/no) 
* If yes, please list some of relevant laws that the project complies with:
* If yes, please describe the steps this project has taken to ensure adherence (include links to terms of service, privacy policy, or other relevant documentation):

**Comment by christer-io** [comment]
The proposed change has been filed as a PR.

**Comment by lacabra** [comment]
@christer-io can you say which PR number are you referring to? Thanks 🙏

**Comment by christer-io** [comment]
It is in the making, will be posted tomorrow.

**Comment by christer-io** [comment]
Correction. @lacabra I ended up making the change tonight. It is now under PR #37.

**Comment by Lucyeoh** [comment]
This has been implemented.
