### ISSUE TITLE
More specific language pertaining to data or file formats for content and data  

### ISSUE THREAD

**Issue by christer-io** [DPGAlliance/DPG-Standard#48]
I am exploring the implications of accepting or rejecting the proposed change to standard.md. This should trigger a two week community input period that will end February 27. 

I suggest that we include some more specific language around data and file formats to ensure that indicator 8 is more specifically addressing the need for open and documented file and data formats. 

This change would be highly relevant for content and data being vetted against indicator 2.  By being more specific we will ensure to avoid that a content repository/project that has content in an approved open license but at the same time use closed or undocumented file formats, making reuse difficult or impossible.

An example of languages that could make indicator 8 more specific: "Open data and content must be made accessible in an open data or file format, including relevant metadata and documentation.".

**Comment by prajectory** [comment]
Hi, I have moved this over to #59 to get this in tandem with discussions on open data at large so we can have a big picture view of this.

**Comment by prajectory** [comment]
Hi @christer-io I was going through the changes you have suggested as we will discuss them in the standard council meeting. I am thinking, perhaps the last change you have mentioned pertaining to file formats is more relevant for indicator 5 than indicator 8. That said, if you think otherwise, let me know!

**Comment by prajectory** [comment]
We have taken two steps from this:

- [ ] Changes to indicator 6 - we have clearly defined that the mechanism for extracting data needs to be non-proprietary and we also make sure it gets reviewed through the vetting process
- [ ] FAQ/ Best practices for documentation that can be made available to keep away from proprietary softwares and formats 

We are closing this particular issue for now. Have put this into action.
