### ISSUE TITLE
Planning of V.2 of the DPG standard

### ISSUE THREAD

**Issue by christer-io** [DPGAlliance/DPG-Standard#49]
During this week's meeting (on Feb 18), we start our planning towards version 2 of the DPG standard. The idea is to have an open discussion that leads to a version plan that includes:
* Mayor potential changes to the standard
* A planned release date
* A plan with dates for community input to the process and proposed changes

**Comment by Lucyeoh** [comment]
Consider #57 as component of V2

**Comment by christer-io** [comment]
Closing this issue - initiating V2 wiki.
