### ISSUE TITLE
Multi selector for license in standard-questions.md

### ISSUE THREAD

**Issue by christer-io** [DPGAlliance/DPG-Standard#53]
This issue concerns standard-questions.md and "DPGs must use an open license. Please identify which of these approved open licenses this project uses:" 

The text above refers to "licenses" in plural, and that is correct, as both software project, content, AI and data projects can use more than one license. The issue is that the submission form only allows the user to choose one license. 

Suggested change: Change the drop-down in the form to another field type that allows the user to choose more than one license. 

We might also want to change the first sentence in the form text "DPGs must use an open license" as this refers to only one license.

**Comment by lacabra** [comment]
Agreed. This is partly a limitation of the current implementation and a usability issue. The Google Form would only allow multiple options through checkboxes, which would make that question excruciatingly long.

This is a feature that is on hold until the release of the new form that is in active development.
