### ISSUE TITLE
DPG reference catalog for standards & best practices

### ISSUE THREAD

**Issue by christer-io** [DPGAlliance/DPG-Standard#56]
Based on recent discussions in the DPG secretariat I am now suggesting that we start the process of defining the DPG reference catalog for open standards.  

This reference catalog would be an overview of standards that are recommended for Digital Public Goods. The standards can be technical or semantic. 

I have created a PR (#55) where I have created a first very early draft of the reference catalog just to get us started in the process of defining a complete list. 

I would suggest we add this to our work on version 2 of the DPG Standard to ensure involvement for all relevant stakeholders.

**Comment by Lucyeoh** [comment]
- Decision on whether to include a list of standards
- Decision on whether to offer those standards as examples or as requirements
- Decision on whether to curate our own list of individual standard or point to others
- Decisions on what to put in those standards if we curate our own list

**Comment by Lucyeoh** [comment]
Status: 
* Draft has been created

Next steps: 
* Add to the resource site.

**Comment by nathanbaleeta** [comment]
[DPG Reference catalog for open standards (2).docx](https://github.com/DPGAlliance/DPG-Standard/files/6318718/DPG.Reference.catalog.for.open.standards.2.docx)

**Comment by Lucyeoh** [comment]
Add to list of "Principles" - for "Data" cite the ‘FAIR Guiding Principles for scientific data management and stewardship’ were published in Scientific Data. https://www.go-fair.org/fair-principles/

**Comment by Lucyeoh** [comment]
Linking #88 "SDLC, SSDLC, OWASP/ ASVS, ISO/IEC 27k, some of these further covered under my paragraph “Summary and a few thoughts.”. Depending on the project, there might be other standards, best practices or principles that might be more applicable or better suited."

**Comment by prajectory** [comment]
#107 will execute these changes with a .MD on the repo that will contain the reference catalogue that we can build on.
