### ISSUE TITLE
[Proposal] Retrofit the standards for Open Data, Open Standards

### ISSUE THREAD

**Issue by Lucyeoh** [DPGAlliance/DPG-Standard#59]

**Comment by prajectory** [comment]
@Lucyeoh Does this also relate with #48 ?

**Comment by prajectory** [comment]
@christer-io has some inputs he has given another issue, I am linking that here its its relative. 

I am exploring the implications of accepting or rejecting the proposed change to standard.md. This should trigger a two week community input period that will end February 27.

I suggest that we include some more specific language around data and file formats to ensure that indicator 8 is more specifically addressing the need for open and documented file and data formats.

This change would be highly relevant for content and data being vetted against indicator 2. By being more specific we will ensure to avoid that a content repository/project that has content in an approved open license but at the same time use closed or undocumented file formats, making reuse difficult or impossible.

An example of languages that could make indicator 8 more specific: "Open data and content must be made accessible in an open data or file format, including relevant metadata and documentation.".

#48

**Comment by prajectory** [comment]
https://github.com/DPGAlliance/DPG-Standard/issues/122

**Comment by prajectory** [comment]
Adding relevant issues: https://github.com/DPGAlliance/DPG-Standard/issues/123

**Comment by prajectory** [comment]
Adding relevant issues: https://github.com/DPGAlliance/DPG-Standard/issues/111

**Comment by shubrank** [comment]
Test

**Comment by prajectory** [comment]
closing this issue, please follow #126 for all updates on this front.
