### ISSUE TITLE
Update Summary Indicator Text for "Do No Harm" 

### ISSUE THREAD

**Issue by Lucyeoh** [DPGAlliance/DPG-Standard#65]
Current  Indicator # 9 = Do No Harm (encompasses 9a,9b,9c)

Proposal = Steps Taken to Mitigate & Avoid Harm 

The reason for this is that many solutions have expressed discomfort with the concept of assuring that they "do no harm" as they are open source solutions, there is not visibility into who and how the products are deployed or implemented. 

This revised wording for indicator 9 allows solutions to describe the steps taken as part of the design and development of the solution to mitigate and avoid harm. Note that this is relevant but distinct from PR #70

**Comment by Lucyeoh** [comment]
As per the Standard Governance this issue is now open for two weeks for additional input from the community. We will inform the members of the DPGA's Internal Strategy Group (ISG) giving them an equal opportunity to comment. Reviewing these changes will happen quarterly. Consensus from the 2 co-leads and 2 technical leads (see Current Roles) will be required to accept or reject these proposals.

**Comment by tanuj-b** [comment]
> Current Indicator # 9 = Do No Harm (encompasses 9a,9b,9c)
> 
> Proposal = Steps Taken to Mitigate & Avoid Harm
> 
> The reason for this is that many solutions have expressed discomfort with the concept of assuring that they "do no harm" as they are open source solutions, there is not visibility into who and how the products are deployed or implemented.
> 
> This revised wording for indicator 9 allows solutions to describe the steps taken as part of the design and development of the solution to mitigate and avoid harm. Note that this is relevant but distinct from PR #70

Without having read this, this is exactly what I recommended for privacy in #69 too. Let the creators indicate what they have done to protect privacy/prevent harm, rather than having them certify it as "privacy compliant" or "doing no harm".

**Comment by Lucyeoh** [comment]
"Do No Harm By Design" 

Re-write - All projects must demonstrate that they have taken steps to mitigate and avoid harm.

**Comment by nathanbaleeta** [comment]
> "Do No Harm By Design"
> 
> Re-write - All projects must demonstrate that they have taken steps to mitigate and avoid harm.
> 
> @nathanbaleeta

@Lucyeoh I'm in agreement.

**Comment by Lucyeoh** [comment]
Now in PR #79
