### ISSUE TITLE
Form Suggestion: SDG Question

### ISSUE THREAD

**Issue by Lucyeoh** [DPGAlliance/DPG-Standard#67]
For the SDG question we propose changing the prompt word from "description" to "explain how this solution is relevant"

**Comment by Lucyeoh** [comment]
Clarification: 

In order to get better evidence for SDG support propose requiring a an explanation for how the solution is relevant with optional URL.

**Comment by nathanfletcher** [comment]
Hi Lucy, just to confirm before I push. 
This is the question and change to be done, right? [screenshot below]
![Screenshot 2021-07-09 at 11.08.03 AM.png](https://images.zenhubusercontent.com/60c9f3c5e24126113185cd7b/a7737cff-227b-4713-85d6-afcb4f9a11de)

**Comment by nathanfletcher** [comment]
Hey Lucy, just to confirm before I push, this is the change to be made
![Web capture_9-7-2021_112730_localhost.jpeg](https://images.zenhubusercontent.com/60c9f3c5e24126113185cd7b/d7423078-94b8-4b38-a274-b09c23cfa7af)

**Comment by lacabra** [comment]
@nathanfletcher the proposed fix looks good to me

@Lucyeoh this issue does not technically belong to this repository (and hence the `minor fix` label does not apply). This should belong to the [submission form repository](https://github.com/lacabra/submission-digitalpublicgoods) where the user interface is implemented.

**Comment by Lucyeoh** [comment]
Closing on behalf of @nathanfletcher
