### ISSUE TITLE
Expansion of the Intro text for the DPG Standard

### ISSUE THREAD

**Issue by Lucyeoh** [DPGAlliance/DPG-Standard#71]
To include: 
* Glossary of relevant terms
* Explanation of how project/product fits with the term DPG

**Comment by Lucyeoh** [comment]
Updated [DPG Standard Intro text draft.](https://docs.google.com/document/d/1EFr8YZlz3-MBps2ZibMQE-lSlpBdRvq7wexSdEjmCHs/edit?usp=sharing) 
* [Glossary of terms ](https://docs.google.com/document/d/1L2r3fVP6cKy_j7hpsFzfnFzOjH52wyPJMPXg9PvHlFo/edit#heading=h.55n7rwx25ojm)

**Comment by Lucyeoh** [comment]
24 hours to review & comment. If no objections - Jameson will update the website and close the issue.

**Comment by lacabra** [comment]
Looks good to me

**Comment by SarahWat** [comment]
Updated the introduction to the DPG Standard on the website.
