### ISSUE TITLE
Should we keep the "unknown" option in the DPG Nomination Form 

### ISSUE THREAD

**Issue by Lucyeoh** [DPGAlliance/DPG-Standard#77]
For discussion - should we keep the unknown option? Your thoughts?

**Comment by nathanbaleeta** [comment]
@Lucyeoh I would strongly recommend keeping the "unknown" option as it has proven very helpful in gathering better subsequent responses from projects during follow-up.

**Comment by lacabra** [comment]
Yes, I am supportive of keeping the `Unknown` option as long as we agree that it will never be a valid answer to approve a submission as a digital public good, and some of those answers require an explicit `Yes` to become one.

**Comment by Lucyeoh** [comment]
Makes sense to me. Closing
