### ISSUE TITLE
Incorrect spelling of acronyms in the DPG Nomination Form

### ISSUE THREAD

**Issue by surendrasinghs** [DPGAlliance/DPG-Standard#82]
It is "acronymns" --> It should be "acronyms"

Screenshot attached for reference
<img width="584" alt="image" src="https://user-images.githubusercontent.com/10580754/130780732-14d72746-2201-412c-8441-c59433aa2ec5.png">

**Comment by prajectory** [comment]
Thanks @lacabra confirming the change and closing the issue.
