### ISSUE TITLE
Indicator 4. 	Platform Independence

### ISSUE THREAD

**Issue by llsandell** [DPGAlliance/DPG-Standard#84]
This indicator is too vague in my opinion, “demonstrate” and “indicated” are both pretty abstract words you can fill with just about anything. There are plenty of examples showing there can be huge gaps between what could work in theory, and what actually works in real life. This is true, both for small agile IT-projects and huge governmentally run projects spending millions in planning, preparation and execution. I would strongly urge that the word “indicate” is replaced by “prove” or that the sentence is changed to “…..list existing fully functional, open alternatives”, to avoid good projects being shut down by poor planning.

**Comment by prajectory** [comment]
When the digital public good has mandatory dependencies that create more restrictions than the original license, demonstrating independence from the closed component(s) and/or **proving** the existence of functional, open alternatives is required.

Does the above mentioned text look good to you?

**Comment by prajectory** [comment]
https://github.com/DPGAlliance/DPG-Standard/issues/57 Changes being tracked here.
