### ISSUE TITLE
Indicator 6.	Mechanism for Extracting Data

### ISSUE THREAD

**Issue by llsandell** [DPGAlliance/DPG-Standard#86]
I would change this to: 
“If the project has non-personally identifiable information (non-PII) there must be a possibility for extracting or importing non-PII data from the system in a non-proprietary format”. It would be advisable to either include a list of approved formats, or include examples of non-proprietary formats. I would avoid using the word “mechanism” here, see Indicator 9.b for explanation

**Comment by prajectory** [comment]
Very valid input and appreciate you thinking about it from user POV so rigorously. 

It's changed to: 
Digital Public Goods with non personally identifiable information (PII) must design for possibility of extracting or importing non-PII data and content from the system in a non-proprietary format.

You can track this progress in this change on this issue. https://github.com/DPGAlliance/DPG-Standard/issues/57 

I am closing this issue in the meanwhile.
