### ISSUE TITLE
Indicator 8.	Adherence to Standards & Best Practices

### ISSUE THREAD

**Issue by llsandell** [DPGAlliance/DPG-Standard#88]
I would like it to read: 
“Projects must demonstrate adherence to standards, best practices, and/or principles. For example, the Principles for Digital Development. See list here for reference”

A very good indicator. I would probably prefer to include a list of other standards as well as SDLC, SSDLC, OWASP/ ASVS, ISO/IEC 27k, some of these further covered under my paragraph “Summary and a few thoughts.”. Depending on the project, there might be other standards, best practices or principles that might be more applicable or better suited. 

It would also be advisable to develop a best practice regarding DPG for the future.

**Comment by Lucyeoh** [comment]
Great suggestions @llsandell linking this to #56 about developing this catalogue!
