### ISSUE TITLE
Indicator 9.b 	Inappropriate & Illegal Content

### ISSUE THREAD

**Issue by llsandell** [DPGAlliance/DPG-Standard#91]
I would like this to read:
“Projects that collect, process, store or distribute content must have enforceable policies identifying inappropriate and illegal content such as child sexual abuse materials in addition to mechanisms for detecting, moderating, reporting and removing inappropriate/ illegal content”. 

First of all, I added “process”, as in the indicator above, it might not be apparent, but in data processing, additional tasks such as detection, can be added with ease. Secondly, I added “reporting” as there should be a way for users to report undesired content. Community help to moderate, is always preferable. 

My worries here are the latter part of the indicator “….materials in addition to mechanisms for detecting, moderating, and removing inappropriate/ illegal content”. The intentions are good and there is an obvious need for having such functions in place. For most people working in computing, the term mechanism or computing mechanism, describes a mechanism whose function is to generate output strings from input strings and if applicable, internal states, in accordance with a general rule that applies to all relevant strings and depends on the input strings and possibly, internal states, for its application. Internal states, refers to “hidden” variables impacting the behavior of the mechanism´s input and output. So, “mechanisms” is by all means a usable term. 

However, having in place mechanisms for “detecting, moderating, and removing inappropriate/ illegal content” is a tall order for any software developer. Even the giants as Facebook struggles to have this in place, as fully functional services. So, I wonder if we can find a more suitable term without compromising the intent of the sentence. Moderating words, phrases or even sentences are pretty easy tasks. Detecting and blocking images being shared, is an entirely other ballgame and can easily make or break a project financially as it is demanding on so many levels.

**Comment by prajectory** [comment]
Hi @llsandell 

Thank you for suggesting these changes. We have made changes to the standard as per these suggestions. 
________

(9b) (9c) Mechanism as a term can be confusing since it has different implications for technologists vs non technologists. Since the standard deals in depth with the design, it is paramount that we clarify any confusion that language may be causing. The Standard Council considered other terms that would be more appropriate - policies, processes, systems.

More details at #120 

Please keep us posted.
