### ISSUE TITLE
DPG standard, general thoughts 

### ISSUE THREAD

**Issue by llsandell** [DPGAlliance/DPG-Standard#93]
There is no point in reinventing the barrel. There are a lot of good standards out there that can be utilized both as inspiration and as a broad dynamic knowledge base for the various communities interested in developing projects within the DPG scope. Amongst them are standards like the SDLC- standard (Software Development Life Cycle) and the SSDLC-standard (Secure Software Development Life Cycle). There are also the standards within the ISO/ IEC 27k series, the international standard entitled: Information technology that can be utilized either by obtaining proper certifications or by “being in compliance with” one, or more of the standards. 

Although far from perfect, the intentions behind the GDPR is amicable. A lot of European countries have high internet penetration rates and are pretty much way ahead of most development countries when it comes to computer literacy, technology development and tech usage. Still it appears as we as citizens in the tech savvy parts of the world, need laws and legislation protecting us from big corporations and data mining, as well as misusage of the data we generate. The needs for privacy and protection do not appear any less for citizens of development countries, quite the contrary.  Datatilsynet´s guide to “Software development with Data Protection by Design and by Default”, deals specifically with software development (as described in article 25 in GDPR) and can be a useful tool even for projects operating outside the EU/ EEC.

**Comment by prajectory** [comment]
What the DPGA is trying to do is find baseline assessment metrics to classify new age digital solutions that are being designed to mitigate the increasingly accelerating challenges threatening world peace and security further stalling progress of LMICs (low and middle income countries). While there are a lot of software standards that govern digital solutions, DPGs can be software, content of data projects. It is therefore difficult to bind them all under one umbrella. 

The standard doesn't use GDPR as the baseline or require projects to comply with it. DPGs have to comply in principle of design with privacy laws but those can be laws relevant to the DPGs geographical location and other aspects. DPGA is mindful about EU based laws and standards are not used as a universal measure in any way. Hope that clarifies how we view this. Thanks for your contributions and we will always be eager to hear from you! 
-Product Manager, DPGA
