### ISSUE TITLE
Define list of acceptable licenses for DPG type "standard"

### ISSUE THREAD

**Issue by lacabra** [DPGAlliance/DPG-Standard#96]
The DPG standard is very clear in stating which licenses are approved for `software`, `content` and `data` [here](https://github.com/DPGAlliance/DPG-Standard/blob/main/standard.md), namely:

> Projects must demonstrate the use of an approved open license. For open source software, only [OSI approved licenses](https://opensource.org/licenses) are accepted. For open content the use of a [Creative Commons license](https://creativecommons.org/licenses/) is required. While we encourage projects to use a license that allows for both derivatives and commercial reuse ([CC-BY](https://creativecommons.org/licenses/by/4.0/) and [CC-BY-SA](https://creativecommons.org/licenses/by-sa/4.0/)), or dedicate content to the public domain ([CC0](https://creativecommons.org/choose/zero/)); licenses that do not allow for commercial reuse ([CC-BY-NC](https://creativecommons.org/licenses/by-nc/4.0/) and [CC-BY-NC-SA](https://creativecommons.org/licenses/by-nc-sa/4.0/)) are also accepted. For open data, an [Open Data Commons approved license](https://opendefinition.org/licenses/) is required. See [The full license list](https://github.com/unicef/publicgoods-candidates/blob/master/docs/licenses.md) for reference.

Yet, there is no mention of what licenses are approved with the digital public good under consideration refers to a `standard`.

Proposed way forward:
* Identify an authoritative licensing body that we can rely on for choosing acceptable licenses for `standards`
* Amend the text of the standard to explicitly list acceptable licenses to the `standard` type and update [this list](https://github.com/unicef/publicgoods-candidates/blob/master/docs/licenses.md) accordingly.

Cc: @nathanbaleeta

**Comment by AlexLakatos** [comment]
Looking at [one of the DPG standards already accepted](https://github.com/unicef/publicgoods-candidates/blob/main/nominees/standard-for-public-code.json), they have CC0-1.0 as a license. I think that makes sense, I would also expect Creative Commons licenses to be the accepted licenses, because when I boil it down Standards can be interpreted as Content.

**Comment by prajectory** [comment]
The DPG review team gets 1-2 applications every 3-6 months for an open standard to be a vetted DPG. Usually these can be classified under open content. But that leaves them open to the risk of someone forking the project/ making changes to the core of the project. A standard typically can't change and therefore in many cases the text of the standard itself is proprietary. 

While currently, we are solving this case to case basis, it will have to be resolved as we see more 'standards' applying to be a DPG. We are moving this to expert consultation stage and talking to a few experts before we decide what our potential approach could be. 

In the April standard council, we discussed following:

- [ ] Look into ISO/ IEEE certifications as potential options 
- [ ] Consulting with [Standard for Public Code](https://publiccode.net/standard-for-public-code/#:~:text=The%20Standard%20for%20Public%20Code%20gives%20public%20organizations%20a%20model,city%20administrators%2C%20developers%20and%20vendors.) which is a DPG

We will have updates on this thread when we have more details.

**Comment by prajectory** [comment]
Hi @AlexLakatos when the annual reviews are conducted, we will have to update the registry as per these changes which would mean that standards would not be able to function as DPGs.

**Comment by prajectory** [comment]
All public documentation to be updated: https://github.com/DPGAlliance/publicgoods-submission/issues/3 @nathanbaleeta @nathanfletcher will execute this 

Research: other standards to add to evolve indicator 8 

Blog post: we will explain this change more in detail on the blog post

**Comment by prajectory** [comment]
closing this issue, please follow #126 for all updates on this front.
