### ISSUE TITLE
Content > Content Collections

### ISSUE THREAD

**Issue by prajectory** [DPGAlliance/DPG-Standard#97]
If someone submits just one poem or limited amount of data, will that project be considered a digital public good? It may be a good idea to use 'content collections' and 'data collections' instead of content or data wherever it is used in the context of the project across all indicators of the standards.

**Comment by prajectory** [comment]
This change has been executed with approval from all reviewers of the standards governance. Thanks!

**Comment by lacabra** [comment]
@prajectory: where has this been addressed? It would be great to point/link to a PR or a commit that documents this change. Thank you

**Comment by prajectory** [comment]
This will be addressed with Digital Solution change. Should I link this on that PR?

**Comment by prajectory** [comment]
#57 will incorporate this change since it deals with 'sharpening the language'.

**Comment by lacabra** [comment]
All clear, thank you for linking the related issue 🙏
